# Generated by Django 4.2.5 on 2024-01-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg_Name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='product_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDT_Image', models.ImageField(null=True, upload_to='images')),
                ('PRDT_Title', models.CharField(max_length=1000)),
                ('PRDT_price', models.IntegerField(max_length=6)),
                ('PRDT_Description', models.CharField(max_length=10000)),
                ('PRDT_Usage', models.CharField(max_length=10000)),
                ('PRDT_Features', models.CharField(max_length=10000)),
                ('PRDT_Benefits', models.CharField(max_length=10000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.category_db')),
            ],
        ),
    ]
