# Generated by Django 4.2.5 on 2024-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='PRDT_Size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
