# Generated by Django 4.2.5 on 2024-02-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0004_product_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_faq',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
