# Generated by Django 4.2.5 on 2024-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0005_alter_product_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_faq',
            name='PRDT_FAQ_Title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
