# Generated by Django 4.2.5 on 2024-03-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0006_product_faq_prdt_faq_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=5000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.product_db')),
            ],
        ),
    ]
