# Generated by Django 4.2.5 on 2024-03-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0007_product_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Desc',
            new_name='Product_feat',
        ),
    ]
