# Generated by Django 4.2.5 on 2024-03-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0008_rename_product_desc_product_feat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_feat',
            name='PRDT_FAQ_Title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
