# Generated by Django 4.2.5 on 2024-03-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0009_product_feat_prdt_faq_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_feat',
            old_name='PRDT_FAQ_Title',
            new_name='PRDT_FEAT_Title',
        ),
    ]
