# Generated by Django 4.2.5 on 2024-03-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0010_rename_prdt_faq_title_product_feat_prdt_feat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_db',
            name='PRDT_price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.CreateModel(
            name='Product_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDT_FEAT_Title', models.CharField(max_length=1000, null=True)),
                ('use', models.CharField(max_length=5000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.product_db')),
            ],
        ),
    ]
