# Generated by Django 4.2.5 on 2024-03-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0011_alter_product_db_prdt_price_product_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_usage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product_feat',
        ),
        migrations.DeleteModel(
            name='Product_usage',
        ),
    ]
