# Generated by Django 4.2.5 on 2024-03-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0012_remove_product_usage_product_delete_product_feat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDT_USE_Title', models.CharField(max_length=1000, null=True)),
                ('use', models.CharField(max_length=5000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.product_db')),
            ],
        ),
        migrations.CreateModel(
            name='Product_feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDT_FEAT_Title', models.CharField(max_length=1000, null=True)),
                ('Desc', models.CharField(max_length=5000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.product_db')),
            ],
        ),
        migrations.CreateModel(
            name='Product_dsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDT_DSC_Title', models.CharField(max_length=1000, null=True)),
                ('content', models.CharField(max_length=5000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.product_db')),
            ],
        ),
    ]
