# Generated by Django 5.0.2 on 2024-03-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0013_product_usage_product_feat_product_dsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_db',
            name='PRDT_Benefits',
            field=models.TextField(blank='True', null=True),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='PRDT_Description',
            field=models.TextField(blank='True', null=True),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='PRDT_Features',
            field=models.TextField(blank='True', null=True),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='PRDT_Size',
            field=models.CharField(blank='True', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='PRDT_Usage',
            field=models.TextField(blank='True', null=True),
        ),
    ]
