# Generated by Django 5.0.2 on 2024-03-19 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0014_alter_product_db_prdt_benefits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Location',
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'State',
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Trainer_type',
                'db_table': 'Trainer_type',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=10000)),
                ('time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.location')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.state')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.trainer')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.trainer_type')),
            ],
            options={
                'verbose_name_plural': 'Session',
                'db_table': 'Session',
            },
        ),
    ]
