# Generated by Django 5.0.2 on 2024-03-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0015_location_state_trainer_trainer_type_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name_plural': 'Trainer'},
        ),
        migrations.AlterModelTable(
            name='trainer',
            table='Trainer',
        ),
    ]
