# Generated by Django 5.0.2 on 2024-03-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0016_alter_trainer_options_alter_trainer_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='state',
        ),
        migrations.RemoveField(
            model_name='session',
            name='types',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Trainer_type',
        ),
    ]
