# Generated by Django 5.0.2 on 2024-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0019_alter_trainer_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
