# Generated by Django 5.0.2 on 2024-03-27 04:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0021_events_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_type',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
