# Generated by Django 5.0.2 on 2024-03-27 08:53

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0022_alter_trainer_type_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'Branch',
                'db_table': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='state')),
                ('District', models.CharField(max_length=150)),
                ('Address', models.TextField(max_length=20000)),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Olsi_App.branch')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'Branches',
            },
        ),
    ]
