# Generated by Django 5.0.2 on 2024-03-27 09:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Olsi_App', '0023_branch_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='state'),
        ),
    ]
